# MailboxPlugin 配置文件

# 數據存儲配置
storage:
  # 存儲類型: file 或 mysql
  type: "mysql"

# MySQL 數據庫配置
mysql:
  # 數據庫連接信息
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: "password"

  connection-params:
    allowPublicKeyRetrieval: true
    useSSL: false
    serverTimezone: "UTC"
  # 連接池配置
  connection-pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

  # 數據庫表前綴
  table-prefix: "mailbox_"

  # SSL連接 (如果需要)
  use-ssl: false

# 文件存儲配置 (當 storage.type 為 file 時使用)
file:
  # 數據文件夾名稱
  folder-name: "mailboxes"

# 信箱系統配置
mailbox:
  # 自動保存間隔 (分鐘)
  auto-save-interval: 5

  # 每個玩家最大郵件數量
  max-mails-per-player: 100

  # 郵件保存天數 (超過天數自動刪除，-1 表示永不刪除)
  mail-expire-days: 30

  # 通知設置
  notifications:
    # 玩家登錄時是否通知未讀郵件
    notify-on-join: true

    # 通知延遲時間 (tick，20tick = 1秒)
    notification-delay: 40

# 權限設置
permissions:
  # 普通玩家每次最多可以發送的郵件數量
  max-send-per-operation: 64