name: MailboxSystem
version: 1.1
main: me.ninepin.mailBoxPlugin.MailboxPlugin
api-version: 1.16
description: 一個提供信箱功能的插件
softdepend: [PlaceholderAPI]
author: niepin

commands:
  mail:
    description: 信箱系統主命令
    usage: /mail [box|all|give|help]
    aliases: [ mailbox ]
    permission: mailbox.use

permissions:
  mailbox.use:
    description: 允許使用基本信箱功能
    default: true
  mailbox.give:
    description: 使用給予功能
    default: true
  mailbox.admin:
    description: 允許使用管理員功能
    default: op
  mailbox.check:
    description: 允許查看其他玩家的信箱
    default: op
  mailbox.admin.manage:
    description: 允許管理員刪除信箱中的物品
    default: false